id: IF7ADEC00
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-29T18:12:24+00:00'
last_modified: '2022-06-08T01:51:36.923628+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W1PD137853
  title: ཉིང་བཅུད་རིག་གནས་སྡོམ་བཤད།
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  base:
    6DDA:
      image_group_id: I2PD20380
      title: ''
      total_pages: 502
      order: 1
      base_file: 6DDA.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
