id: P004548
initial_creation_type: ocr
created_at: 29/03/2020
last_modified_at: 2021-12-17 11:41:09.843405
source_metadata:
  id: bdr:W1PD137853
  title: ཉིང་བཅུད་རིག་གནས་སྡོམ་བཤད།
  author: ''
  volumes:
    bc0a84f41a2843d68e548e2dbfb09b79:
      image_group_id: I2PD20380
      title: ''
      volume_number: 1
      total_pages: 502
      base_file: v001.txt
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
