id: P004548
initial_creation_type: ocr
source_metadata:
  id: bdr:W1PD137853
  title: ཉིང་བཅུད་རིག་གནས་སྡོམ་བཤད།
  author: ''
  volumes:
    bc0a84f41a2843d68e548e2dbfb09b79:
      image_group_id: I2PD20380
      title: ''
      volume_number: 1
      total_pages: 502
      base_file: v001.txt
